# Generated by Django 4.2 on 2023-10-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('author', models.CharField(max_length=150, verbose_name='author')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
        ),
    ]
