# Generated by Django 4.2 on 2023-10-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readscore', '0002_rename_books_book_readingsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
