# Generated by Django 4.2 on 2023-10-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readscore', '0003_book_end_time_book_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_of_last_reading',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
