# Generated by Django 4.2 on 2023-10-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readscore', '0004_book_date_of_last_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_of_last_reading',
            field=models.IntegerField(blank=True, default=0, verbose_name='date_of_last_reading'),
        ),
    ]
