# Generated by Django 4.2 on 2023-10-16 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readscore', '0005_alter_book_date_of_last_reading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='book',
            name='start_time',
        ),
    ]
