# Generated by Django 4.2 on 2023-10-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readscore', '0006_remove_book_end_time_remove_book_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_of_last_reading',
            field=models.DurationField(blank=True, default=0, verbose_name='date_of_last_reading'),
        ),
    ]
