# Generated by Django 4.2 on 2023-10-18 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('readscore', '0007_alter_book_date_of_last_reading'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_for_7_days', models.DurationField(verbose_name='reading_for_7_days')),
                ('reading_for_30_days', models.DurationField(verbose_name='reading_for_30_days')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readscore.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
