# Generated by Django 4.2 on 2023-10-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readscore', '0008_readingstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingstats',
            name='reading_for_30_days',
            field=models.DurationField(blank=True, default=0, verbose_name='reading_for_30_days'),
        ),
        migrations.AlterField(
            model_name='readingstats',
            name='reading_for_7_days',
            field=models.CharField(max_length=150, verbose_name='reading_for_7_days'),
        ),
    ]
