# Generated by Django 4.2 on 2023-10-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readscore', '0009_alter_readingstats_reading_for_30_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingstats',
            name='reading_for_7_days',
            field=models.DurationField(default=0, verbose_name='reading_for_7_days'),
        ),
    ]
